[phases.setup]
nixPkgs = ["nodejs_23", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install", "npm rebuild bcrypt"]

[start]
cmd = "node lib/db.js && node seed-admin.js && node server.js"

